### ISSUE TITLE
insert image size

### ISSUE THREAD

**Issue by parmindersingh1** [cxn03651/write_xlsx#19]
I have generated file of student images and default icon of same pixel size, but when file is generated student images are so small, but icon images   are showing correct size, before write xlsx gem i used write excel gem in which images where showing correctly of same size

**Comment by cxn03651** [comment]
Can you give me source code and image files which causes unexpected result,
please.

cxn03651

2015-04-17 14:04 GMT+09:00 Parminder Singh <notifications@github.com>:

**Comment by andrey-lizunov** [comment]
@cxn03651 I think I have the same issue.
All my images 200x200px, but in generated file they have different sizes
I can provide example and images if it needed.

**Comment by cxn03651** [comment]
send me examples, please.

**Comment by andrey-lizunov** [comment]
@cxn03651 Sent it to email from your github progile. Thx for fasr reply!

**Comment by parmindersingh1** [comment]
i dont have code now

**Comment by andrey-lizunov** [comment]
Here is example of code from my service object, images for test and
screenshots with bug.
Tell me if this info is not enough.

On Mon, Apr 11, 2016 at 7:39 AM, Parminder Singh <notifications@github.com>
wrote:

> i dont have code now
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/cxn03651/write_xlsx/issues/19#issuecomment-208160634>
>



-- 
Best regards,
Andrey Lizunov

**Comment by jmcnamara** [comment]
@andrey-lizunov Could you send me the example images as well so that I can see if there is the same issue in Excel::Writer::XLSX.

**Comment by andrey-lizunov** [comment]
@jmcnamara Sent it to email from your github profile.

**Comment by jmcnamara** [comment]
@andrey-lizunov I ran a sample Excel::Writer::XLSX program with your sample images and got the same results as write_xlsx.

However, as far as I can tell (and there are a lot of tests in both modules to confirm this) the results are correct.

They reason that the images appear at different sizes is that they have different resolutions. Specifically in the case of the 3 images you supplied: 100 dpi, 94 dpi and 300 dpi. Excel scales these images based on a default resolution of 96 dpi and as a result the images appear at different sizes even though they are all 200x200 pixels.

This is exactly the same behaviour you would see if you manually inserted the images into Excel. You can try that to confirm.

This behaviour did change over a year ago in Excel::Writer::XLSX (and probably in write_xlsx) since it didn't take into account the DPI of images. However, that was a bug. The module now behaves like Excel.

I hope that helps clear up the reason for the differences even if it will probably make more work for you to handle files with different resolutions. You could probably scale them all to the same 200x200 size if you worked out the resolution of each and scaled it to 96 dpi using the x_scale and y_scale in `insert_image()`.
