### ISSUE TITLE
undefined method keep_leading_zeros()

### ISSUE THREAD

**Issue by lwyszomi** [cxn03651/write_xlsx#22]
I want keep loadinf zeros (eg: 01234) in cells but method keep_leading_zeros does not exist.

**Comment by joshuapinter** [comment]
You're right. Oddly enough it's in the documentation:

<img width="351" alt="screenshot 2018-08-31 13 49 23" src="https://user-images.githubusercontent.com/180819/44932993-b9a7a600-ad24-11e8-8c2c-696cbac2e394.png">

But the link doesn't actually go anywhere. 

And if you search in the code base, there is no occurrences of `keep_leaking_zeros` at all.

So, it must have been copied over in the docs but never implemented.

FWIW, you can use `write_string` to keep leading zeros on values like `0001`.

In our case, we were using `write_row` and there's now way to specify that it should use `write_string` instead of `write` when outputting each column. So, I forked this repo and modified it so that by default `write_row` will always use `write_string`, keeping leading zeros.

You can see the fork here: 

https://github.com/joshuapinter/write_xlsx

If you want the same thing, you can use this fork in your `Gemfile` with the following: 

```ruby
gem "write_xlsx", github: "joshuapinter/write_xlsx"
```

**Comment by cxn03651** [comment]
thanks for using write_xlsx gem.
Worksheet#keep_leading_zeros method has just been added in v1.09.1.
