### ISSUE TITLE
Can we force a cell to have string format?

### ISSUE THREAD

**Issue by LaurentSHB** [cxn03651/write_xlsx#23]
In order to not have the same problem as #22 , is there a way to force a cell to have the string format?

I have some value which have "01" or "001" which are not numeric but string in my database so I want to keep this format with zeros (in order to import the file after). `num_format` is not the good option because when I import this file I have "1" as value but not "01".

**Comment by franckverrot** [comment]
Is `write_string` (instead of `write`) what you're looking for?

**Comment by joshuapinter** [comment]
As I wrote on #22, `write_string` works great but we were using `write_row` and there's no way of specifying that method to use `write_string` instead of `write` so I created a fork of this library that uses `write_string` by default when calling `write_row`. 

You can see the fork here: 

https://github.com/joshuapinter/write_xlsx

If you want the same thing, you can use this fork in your `Gemfile` with the following: 

```ruby
gem "write_xlsx", github: "joshuapinter/write_xlsx"
```

**Comment by cxn03651** [comment]
thank you for using write_xlsx.
Worksheet#keep_leading_zeros method has just been added in v1.09.1.
